TICK_RATE = 50
TICK_TIME = 1 / TICK_RATE

PLAYER_SPEED_PER_TICK = 1
PLAYER_JUMP_HEIGHT = 20
PLAYER_INVISIBLE_TEXTURE_COLOR = (0, 255, 0)
PLAYER_TEXTURE_HEIGHT = 5
PLAYER_TEXTURE_WIDTH = 5
PLAYER_FRICTION_FORCE = 2

DISPLAY_HEIGHT = 600
DISPLAY_WIDTH = 900

GRAVITY = 1